### ISSUE TITLE
Crash in cklib on Kotlin 1.9.20

### ISSUE THREAD

**Issue by swankjesse** [touchlab/cklib#12]
I attempted to upgrade Zipline to Kotlin 1.9.20.
https://github.com/cashapp/zipline/pull/1158

It fails during configuration like so:

```
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.konan.target.Distribution.<init>(java.lang.String, boolean, java.lang.String, java.util.Map, int, kotlin.jvm.internal.DefaultConstructorMarker)'
        at co.touchlab.cklib.gradle.CKlibGradleExtensionKt.getPlatformManager(CKlibGradleExtension.kt:54)
        at co.touchlab.cklib.gradle.CompileToBitcodeExtension.create(CompileToBitcodeExtension.kt:35)
        at co.touchlab.cklib.gradle.CompileToBitcodeExtension.create$default(CompileToBitcodeExtension.kt:26)
        at Build_gradle$4.execute(build.gradle.kts:178)
        at Build_gradle$4.execute(build.gradle.kts:176)
        at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
        at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
        at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:210)
        at org.gradle.kotlin.dsl.Accessors6n6fum4pul64pcchdg9wbot0tKt.cklib(Unknown Source)
        at Build_gradle.<init>(build.gradle.kts:176)
        at Program.execute(Unknown Source)
```

**Comment by shadmanadman** [comment]
Kotlin `2.1.10`
I have the same problem. Any suggestion please?

**Comment by KevinSchildhorn** [comment]
Hi sorry following back up on this. Is this still an issue?

**Comment by swankjesse** [comment]
No longer impacting me.

**Comment by KevinSchildhorn** [comment]
Sounds good, I'm closing the issue then.
