### ISSUE TITLE
Kotlin 1.6-compatible release

### ISSUE THREAD

**Issue by JakeWharton** [touchlab/cklib#3]
Tracking issue

**Comment by swankjesse** [comment]
FYI, if you attempt to use cklib 1.5.31.4 with Kotlin 1.6.10, you might see this crash:

```
* Exception is:
java.lang.ClassNotFoundException: org.jetbrains.kotlin.konan.target.PlatformManager
	at co.touchlab.cklib.gradle.reflection.PlatformManager.<init>(PlatformManager.kt:28)
	at co.touchlab.cklib.gradle.CKlibGradleExtensionKt.getPlatformManager(CKlibGradleExtension.kt:28)
	at co.touchlab.cklib.gradle.CompileToBitcodeExtension.create(CompileToBitcodeExtension.kt:33)
	at co.touchlab.cklib.gradle.CompileToBitcodeExtension.create$default(CompileToBitcodeExtension.kt:24)
	at Build_gradle$2.execute(build.gradle.kts:155)
	at Build_gradle$2.execute(build.gradle.kts:6)
	at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
	at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
	at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:194)
	at org.gradle.kotlin.dsl.Accessors6n6fum4pul64pcchdg9wbot0tKt.cklib(Unknown Source)
	at Build_gradle.<init>(build.gradle.kts:154)
```

**Comment by kpgalligan** [comment]
Release for 1.6.0+ versions. Not (as) directly tied to Kotlin releases, so the version numbering system reverting a bit.

https://github.com/touchlab/cklib/releases/tag/0.2.4

Creating a PR for above project in a bit. Waiting on build...
