### ISSUE TITLE
Crash when Konan classes aren’t downloaded yet

### ISSUE THREAD

**Issue by swankjesse** [touchlab/cklib#5]
I’m seeing this in CI for Zipline, and can reproduce locally by deleting my local Konan directory.

```
$ rm -rf ~/.konan/kotlin-native-prebuilt-*
$ ./gradlew build --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jwilson/Projects/zipline/zipline/build.gradle.kts' line: 155

* What went wrong:
org.jetbrains.kotlin.konan.target.PlatformManager

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.ClassNotFoundException: org.jetbrains.kotlin.konan.target.PlatformManager
        at co.touchlab.cklib.gradle.reflection.PlatformManager.<init>(PlatformManager.kt:28)
        at co.touchlab.cklib.gradle.CKlibGradleExtensionKt.getPlatformManager(CKlibGradleExtension.kt:28)
        at co.touchlab.cklib.gradle.CompileToBitcodeExtension.create(CompileToBitcodeExtension.kt:33)
        at co.touchlab.cklib.gradle.CompileToBitcodeExtension.create$default(CompileToBitcodeExtension.kt:24)
        at Build_gradle$2.execute(build.gradle.kts:155)
        at Build_gradle$2.execute(build.gradle.kts:6)
```

**Comment by veyndan** [comment]
Still running into this on fresh clones of zipline.

**Comment by kpgalligan** [comment]
Anybody know if this is still happening in zipline? I did a clean clone build with the deleted local konan dir and it didn't crash.

It's still an issue with the library, I'm sure. We're assuming kotlin native has been downloaded already. I want to see if there's a way to get the download to happen before we need it, or to just ship the jar with cklib. The issue is that we're using a jar that kotlin native doesn't post as it's own dependency, so we can't just add it to the gradle config. It also may be feasible to delay calling it until after task config. Looking at it now, but if the builds aren't failing, it's a different priority.

**Comment by swankjesse** [comment]
We had this crash when we set up Zipline on a new hire’s workstation a couple weeks ago. I’m setting up a new workstation tomorrow; I’ll post an update here either way.

**Comment by kpgalligan** [comment]
Any particular branch in zipline? I've been trying `jwilson.0105.kt_16`, assuming that's the config that will be in place for 1.6.10.

**Comment by adrw** [comment]
I ran into this today:
```* Exception is:
java.lang.ClassNotFoundException: org.jetbrains.kotlin.konan.target.PlatformManager
	at co.touchlab.cklib.gradle.reflection.PlatformManager.<init>(PlatformManager.kt:28)
	at co.touchlab.cklib.gradle.CKlibGradleExtensionKt.getPlatformManager(CKlibGradleExtension.kt:28)
	at co.touchlab.cklib.gradle.CompileToBitcodeExtension.create(CompileToBitcodeExtension.kt:33)
	at co.touchlab.cklib.gradle.CompileToBitcodeExtension.create$default(CompileToBitcodeExtension.kt:24)
	at Build_gradle$2.execute(build.gradle.kts:155)
```

**Comment by adrw** [comment]
This happens when Zipline is the first KMM project you set up.

**Comment by 05nelsonm** [comment]
I was experiencing this issue as well with my CI tasks, especially when some `sysroot` dependencies were needed to be downloaded, like with Android Native.

Solved it by creating cinterop for all `KotlinNativeTargets` and then adding that task as a dependency for the `CompileToBitcode` task.

- Add to project module a `cklib-dl.def` file
```
# This is here to add the cinterop task generated as a dependency
# of CKLib's CompileToBitcode task for all relevant KotlinNativeTarget
# such that the necessary kotlin native dependencies (LLVM, sysroot, etc.)
# are downloaded for that KotlinNativeTarget before CompileToBitcode is
# executed. See: https://github.com/touchlab/cklib/issues/5
package = your.pkg.name.here.does.not.matter
---
static int
download_kn_dependencies_for_cklib()
{
  return 0;
}
```
- Add the cinterop task to the `test` compilations of all your kotlin native targets and add 
  as a dependency task for the `CompileToBitcode` task.
```
kotlin {
    val cinteropTaskInfo = targets.filterIsInstance<KotlinNativeTarget>().map { target ->
        target.compilations["test"].cinterops.create("cklib-dl") {
            definitionFile.set(projectDir.resolve("$name.def"))
        }.interopProcessingTaskName to target.konanTarget
    }

    project.extensions.configure<CompileToBitcodeExtension>(cklib) {

        // ...

        create("your compilation") {
            val kt = KonanTarget.predefinedTargets[target]!!
            cinteropTaskInfo.forEach { (taskName, target) ->
                if (target.konanTarget != kt) return@forEach
                this.dependsOn(taskName)
            }

            // ...
        }
    }
}
```

**Comment by KevinSchildhorn** [comment]
Sorry for a very late response. Is this considered closed if there's a solution involving `KotlinNativeTargets`?

**Comment by KevinSchildhorn** [comment]
Closing this as there was no response.
